### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by SHXRKIEgg** [yungnickyoung/YUNGs-Better-Dungeons#12] opened 2021-09-09 22:39 UTC
Testing with Better Minecraft Fabric, it crashes but doesn't give me a Crash report but reports it in the log.
https://pastebin.com/Nc7MKd1L

**Comment by yungnickyoung** [comment] 2021-09-09 23:28
This `Accessing PalettedContainer from multiple threads` bug is something that started popping up in 1.17. Seems to be some obscure side effect to one of the changes Mojang made. I thought I had implemented a workaround, but looks like I missed a few spots. I'll upload a fixed version soon

**Comment by yungnickyoung** [comment] 2021-09-11 00:29
Should be fixed in v1.0.1. Let me know if it works!

**Comment by itsdinkd** [comment] 2021-09-11 00:36
Could this be caused by Charm?

![image](https://user-images.githubusercontent.com/35115304/132930337-e472152a-912b-4dd0-9492-fe582e848f0b.png)

**Comment by SHXRKIEgg** [comment] 2021-09-11 02:32
> Should be fixed in v1.0.1. Let me know if it works!

Seems to be fixed thanks!

**Closed as completed** 2021-09-11 02:33 UTC
