### ISSUE TITLE
All dungeon types that have a entrance on the surface can generate in water

### ISSUE THREAD

**Issue by RedrixTTV** [yungnickyoung/YUNGs-Better-Dungeons#27] opened 2022-01-30 01:13 UTC
Sources include
-Oceans
-Lakes
-water pools
-biomes o' plenty rivers separately

In short they shouldn't generate on the surface of water

**Comment by zachsai** [comment] 2022-03-09 20:40
![2022-03-09_15 39 03](https://user-images.githubusercontent.com/63996164/157531942-92419b06-8670-43aa-86d2-3a91d9fd45a2.png)
Same thing happens for me

**Comment by yungnickyoung** [comment] 2022-05-03 19:29
Duplicate of #10

**Closed as completed by yungnickyoung** 2022-05-03 19:29 UTC
